-- ==============================================================================
-- SQL Data Migration Script - B-GUST Ecosystem
-- Group: Clínica El Alfa (Maiquetía)
-- Record count: 153
-- Generated: 2026-07-04 (V2 Update)
-- Charset: latin1 | Collation: latin1_swedish_ci
-- ==============================================================================

CREATE TABLE IF NOT EXISTS personas (
    cedula VARCHAR(255) NOT NULL,
    nombre VARCHAR(255),
    estado VARCHAR(255),
    hospital_refugio VARCHAR(255),
    PRIMARY KEY (cedula)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

LOCK TABLES personas WRITE;
ALTER TABLE personas DISABLE KEYS;

INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('15779885', 'MANUEL ALEJANDRO LEON DURAN', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('10576469', 'CARMEN YELITZA ALDANA SANCHEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('22281788', 'YUBISAY DE CARMEN ALEMAN BELLO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('84316725', 'ALI ALI', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('2552118', 'RUBEN ARTURO ALVIAREZ NOGUERA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('14073944', 'WILKA ELENA ANGARITA MASS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('20190905', 'OMAR JOSE ANZOATEGUI HERNANDEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('27042287', 'GILMARY GABRIELA AREVALO ZERPA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('3614414', 'GLADYS HAYDEE ARTEAGA DE SANCHEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('v2_cl_nica_el_alfa_maiquet_a_0001', 'LEYDI AVENDAÑO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('19273127', 'RAYMAR LORENA AZUAJE PEREZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('24805416', 'ARNALDO LUVI BARRETO CHIRINOS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('6800342', 'YUSMARY BARRIA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('E8156560', 'PEDRO BARRIA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('11063663', 'ISIS DEL CARMEN BARRIOS DIAZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('16105945', 'MARIA FERNANDA BELLORIN YEPEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('11641405', 'HERNEY COROMOTO CALDERON GONZALEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('10584155', 'ANTONIA COROMOTO CAMACHO HERNANDEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('v2_cl_nica_el_alfa_maiquet_a_0002', 'LUIS CARABALLO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('12866921', 'LUZBAUDI CARABALLO SOAZO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('v2_cl_nica_el_alfa_maiquet_a_0003', 'SUSEJ CARDERON', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('5578402', 'LUIS OSWALDO CARREÑO MOYA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('4115714', 'GLORIA MORELA CASTILLO VILLASANA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('5576096', 'CARMEN DOLORES CATARIS JIMENEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('8174231', 'NELSON CHACON', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('12163021', 'WILLIAMS RODOLFO CHIRINOS PEÑA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('19914539', 'MICHAEL CLAROS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('20558013', 'KATHERINE COLMENARES', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('4558009', 'MIRIAM ASUNCION CONTRERAS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('6491384', 'ROGELIO D\' SOUZA OLIVAREZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('10575462', 'OFELIA DELGADO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('31655863', 'GRABIELA DIAZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('6490730', 'ESTHER CAROLINA DIAZ ARTEAGA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('30456047', 'MARIA ALEJANDRA DIAZ GONZALEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('9999907', 'JORGE MANUEL DOS RAMOS SARDINHA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('24609917', 'DIAMANTE ESCALONA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('5091690', 'LUIS ENRIQUE ESCALONA GONZALEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('6794913', 'JOSE ENRIQUE ESCALONA OLIVERO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('7998443', 'WILLIAM ESCOBAR', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('6469315', 'RICHARD DAVID ESCOBAR', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('642662', 'YOTHELI ESCOBAR', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('3611244', 'FLOR MARIA ESCULPI', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('470206', 'LUZMARY ESTE', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('17482664', 'VERUSKA VIRGINIA FLORES', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('25403668', 'LUIS DAVID FONSECA GARCIA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('13910457', 'YOHANA CRISTINA FREITES CONTRERAS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('20558665', 'ISMAR CAROLINA GALDONA BRITO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('23165203', 'NICOLAS GARCIA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('13042097', 'DANI JAKELINE GARCIA MARTINEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('20784405', 'OZZIER ALBERTO GARCIA RIVAS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('23565273', 'NICOLAS JOSE GARCIA RODRIGUEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('31291435', 'MARIANA GARCIAS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('12162722', 'HERNÁN DARWIN GONZALEZ HENRIQUEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('13375230', 'LILIANA JOSEFINA GONZALEZ NATERA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('20558083', 'BARBARA LUCIA GRANADOS ESCALONA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('v2_cl_nica_el_alfa_maiquet_a_0004', 'GUILLERMO GUERRA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('16725167', 'VANESSA DEL CARMEN GUERRIER RODRIGUEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('13930176', 'ORLANDO GUILLEN', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('6483050', 'EGLY DEL VALLE GUILLEN', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('1803703', 'RAFAEL GUTIERREZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('30969851', 'VICTORIA DE LOS ANGELES GUZMAN MONTOYA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('28013076', 'YELIMAR DE JESUS HERNANDEZ BASTARDO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('5519750', 'OMAIRA PASTORA HERRERA SILVA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('E82288910', 'QUANHUI JI', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('9998049', 'FRANKLIN MARTIN JIMENEZ FALCON', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('E1127593083', 'SANDRA JULIO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('4558627', 'ALEXIA JACINTA LIENDO RADA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('20780471', 'ARIANNE LINARES', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('26648853', 'DHAMELYS ANAYS LONGAS LOPEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('27904081', 'JONAIKER JOSE LOPEZ QUEZADA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('17155106', 'ALMER WILER LOPEZ SANDOVAL', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('14314317', 'ANTONIO JOSE LORETO MENDOZA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('458727', 'ESTELA LUGO DE BELLO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('14769904', 'KAREN ALEXA LUNA SALAZAR', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('4559411', 'MERCEDES MARGARITA LUNAR ZAPATA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('5092851', 'ENIS AGUSTINA LUNAR ZAPATA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('v2_cl_nica_el_alfa_maiquet_a_0005', 'ANDREA LUQUE', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('9994428', 'NELSON RAFAEL MAGALLON RODRIGUEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('14312249', 'JOSÉ MARCANO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('34064096', 'ASHLEY MARIN', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('14314312', 'ANAIS MARIN MARIN', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('12828985', 'JAIRO JOSE MARQUEZ GONZALEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('5098926', 'VICTORIA MARTINEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('v2_cl_nica_el_alfa_maiquet_a_0006', 'MIA MARTINEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('10857794', 'JAVIER SIMON MARTINEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('17489136', 'JHON MARTINEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('18534', 'YOLEISY MARTINEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('21192394', 'ASHEIYIX IVANNESKA MARTINEZ ALBARRACIN', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('20559188', 'DANIEL MARTINEZ CABRERA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('30824976', 'ISABELLA DAYANY MARTINEZ NAVAS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('13672531', 'YSAIAS GREGORIO MATA PEREZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('33356556', 'ANGEL MAYORA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('26647135', 'JORGELIS YESIBET MEDINA IZAGUIRRE', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('16507942', 'KRISTEY MEIRELLES', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('v2_cl_nica_el_alfa_maiquet_a_0007', 'YONJAIBER MENDEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('26223960', 'ORIANNY LISETH MENDEZ HERNANDEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('14071402', 'YONJAIBER MENDEZ NUÑEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('1564264', 'RENE MILO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('29521312', 'KIMBERLY NORELIS MONTAÑO DURAN', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('7990358', 'JUAN RICHARD MONTEBUGNOLI', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('30170401', 'ALAM MARCOS MONTERO SUAREZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('3365140', 'EULOGIA EMILIA MORA DE ALGARIN', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('17154563', 'YASMIN CAROLINA MOSQUEDA LOPEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('17710692', 'LIHARKO JOSE NAVARREZ GUTIERREZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('20005007', 'ANDREA CAROLINA NAVARRO JASPE', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('12163090', 'YNDIRA CAROLINA NIETO FLORES', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('6483930', 'JOSE ALEJANDRO OROPEZA LAEMAN', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('20006075', 'AROSKA JOSE OROZCO HERNANDEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('15779486', 'EMMANUEL ORTA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('27233630', 'JOSE VENTURA ORTEGA VILLALBA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('v2_cl_nica_el_alfa_maiquet_a_0008', 'DIEGO PABÓN', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('11056312', 'FIDOLO JESUS PABON YZAGUIRRE', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('27047041', 'RAQUEL PALACIOS PINTO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('17150458', 'LILIMAR PAREDES', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('19045018', 'ARNELIA PAVIO MATA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('10243072', 'MARYURI DE JESUS PAVON IZAGUIRRE', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('6123476', 'OSCAR RAMON PERDOMO MATA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('15780604', 'ANAIS DEL VALLE PEREZ RODRIGUEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('7839594', 'ALEXIS RAMON PIÑA DEMEY', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('30633123', 'KARLA VERONICA QUEZADA LOPEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('19797465', 'DIEGO RAMIREZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('v2_cl_nica_el_alfa_maiquet_a_0009', 'NICOLE RIVAS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('17482232', 'WALESKA CAROLINA RIVAS CASTELLANO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('15266828', 'REINA ELISETH RIVERA ROSAL', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('5097687', 'ELIMENIA LEONIDAS RIVERO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('v2_cl_nica_el_alfa_maiquet_a_0010', 'YOLIANGEL RIVERO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('33285924', 'DIEGO RODRIGUEZ A', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('6472226', 'MARISOL RODRIGUEZ CARMONA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('25309528', 'HEIDERSEN RODRIGUEZ R.', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('13044094', 'CARLOS ALFREDO ROJAS BARRIOS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('3365686', 'OLIMPIA BELEN ROMERO DE CONDE', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('8176024', 'MARY DEL CARMEN ROSQUE BERMUDEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('13225916', 'YICEL DEL VALLE RUIZ MARTINEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('31748970', 'VERUSKA SAAVEDRA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('18141702', 'JHEIMIS SALAZAR', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('16726304', 'OSCAR RAMON SALAZAR AULAR', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('28132173', 'GENESIS BERMARI NAHIR SANABRIA MILLAN', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('11642900', 'WILLIAN ALEXANDER SANCHEZ CEBALLOS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('19914000', 'YSA DOUGLIS SANCHEZ MERLO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('30824225', 'MOISES DAVID DE JESUS SANDOVAL RADA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('8176269', 'MIRIAM DEL VALLE SILVA', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('v2_cl_nica_el_alfa_maiquet_a_0011', 'LUCIANO SOTO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('3888275', 'ROSA MARGARITA SOTO DE RIVERO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('30170905', 'ROIKER JESUS SPINOZA SUAREZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('17959042', 'AHMED SUDANW', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('20151995', 'ROSSELY TORREALBA VARGAS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('15779746', 'MARFRED JOSE TORRES LOPEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('20558584', 'GENESIS ORIANA URBAEZ BOLIVAR', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('32543432', 'ADONYS VASQUEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('28013313', 'DANIEL MOISES VIERA VILLALOBOS', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('3363766', 'LUCRECIA VILLARROEL', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('7995910', 'ISMENIA DOMINGA VILLARROEL MARCANO', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);
INSERT INTO personas (cedula, nombre, estado, hospital_refugio) VALUES ('16724682', 'NAIKE MILAGROS ZAMBRANO MARTINEZ', 'encontrado', 'Clínica El Alfa (Maiquetía)') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre), estado=VALUES(estado);

ALTER TABLE personas ENABLE KEYS;
UNLOCK TABLES;
